<div>
  <div class="row">
    <div class="medium-9 columns">
      <div id="LeftPane" runat="server"></div>
    </div>
    <div class="medium-3 columns">
      <div id="RightPane" runat="server"></div>
    </div>
  </div>
  
  <div class="row">
    <div class="medium-12 columns"><div id="TopPane" runat="server"></div></div>
  </div>

  <div class="row">
    <div class="medium-6 columns"><div id="Left50Pane" runat="server"></div></div>
    <div class="medium-6 columns"><div id="Right50Pane" runat="server"></div></div>
  </div>

  <div class="row">
    <div class="medium-4 columns"><div id="Left33Pane" runat="server"></div></div>
    <div class="medium-4 columns"><div id="Center33Pane" runat="server"></div></div>
    <div class="medium-4 columns"><div id="Right33Pane" runat="server"></div></div>
  </div>

  <div class="row">
    <div class="medium-4 columns"><div id="LeftSmallPane" runat="server"></div></div>
    <div class="medium-8 columns"><div id="RightLargePane" runat="server"></div></div>
  </div>

  <div class="row">
    <div class="medium-8 columns"><div id="LeftLargePane" runat="server"></div></div>
    <div class="medium-4 columns"><div id="RightSmalPane" runat="server"></div></div>
  </div>
  
  <div class="row">
    <div class="medium-3 columns"><div id="Left25LeftPane" runat="server"></div></div>
    <div class="medium-3 columns"><div id="Left25RightPane" runat="server"></div></div>
    <div class="medium-3 columns"><div id="Right25LeftPane" runat="server"></div></div>
    <div class="medium-3 columns"><div id="Right25RightPane" runat="server"></div></div>
  </div>

  <div class="row">
    <div class="medium-12 columns"><div id="BottomPane" runat="server"></div></div>
  </div>

</div>