<div>  
  <div class="row"><div class="medium-12 columns"><div id="FooterTopPane" runat="server"></div></div></div>

  <div class="row">
    <div class="medium-3 columns"><div id="Footer1Pane" runat="server"></div></div>
    <div class="medium-3 columns"><div id="Footer2Pane" runat="server"></div></div>
    <div class="medium-3 columns"><div id="Footer3Pane" runat="server"></div></div>
    <div class="medium-3 columns"><div id="Footer4Pane" runat="server"></div></div>
  </div>

  <div class="row"><div class="medium-12 columns"><div id="FooterBottomPane" runat="server"></div></div></div>

  <div class="row">
    <div class="medium-4 columns small-text-center medium-text-left">
      <ul class="footerList">
        <li class="footerTitle">About Us</li>
        <li class="footerItem">
          <a class="footerLink" href="/Who-are-we">Who Are We</a>
        </li>
        <li class="footerItem">
          <a class="footerLink" href="/Jobs-at-Summer-Festival-Guide">Jobs at Summer Festival Guide</a>
        </li>
        <li class="footerItem">
          <a class="footerLink" href="/Contact-Us">Contact Us</a>
        </li>
      </ul>
    </div>
    <div class="medium-4 columns small-text-center medium-text-center">
      <ul class="footerList">
        <li class="footerTitle">Good Stuff</li>
        <li class="footerItem">
          <a class="footerLink" href="/Festival-News">Festival News</a>
        </li>
        <li class="footerItem">
          <a class="footerLink" href="/Festival-Calendar">Event Calendar</a>
        </li>
        <li class="footerItem">
          <a class="footerLink" href="/Reviews">Reviews</a>
        </li>
        <li class="footerItem">
          <a class="footerLink" href="/Interviews">Interviews</a>
        </li>
      </ul>
    </div>
    <div class="medium-4 columns small-text-center medium-text-right">
      <ul class="footerList">
        <li class="footerTitle">Essentials</li>
        <li class="footerItem">
          <a class="footerLink" href="/Tickets">Festival Tickets</a>
        </li>
        <li class="footerItem">
          <a class="footerLink" href="/Competitions">Competitions</a>
        </li>
        <li class="footerItem">
          <a class="footerLink" href="/Survival-Guide">Survival Guide</a>
        </li>
      </ul>
    </div>
  </div>
  
  <div class="row">
    <div class="medium-12 columns">
      <hr />
    </div>
  </div>
</div>