<ul class="right hide-for-small-only">
	<li>
		<a href="#" data-dropdown="drop2" data-options="align: left"><i class="fi-magnifying-glass searchButton"></i></a>
        <div id="drop2" data-dropdown-content class="f-dropdown content small">
            <div id="search">
                <dnn:SEARCH ID="dnnSearch" runat="server" ShowSite="false" ShowWeb="false" EnableTheming="true" Submit="Search" CssClass="SearchButton" />
            </div>
        </div>
    </li>
</ul>