<!-- //
    A custom collection of 283 icons that are stored in a handy web font.
    
    To use the icons remove the rem tags away and and vice-versa to dislay the icons you wish.
    Copy and paste the url of your social media and replace the #
    There any many more social icons available and can be found here:

    http://zurb.com/playground/foundation-icon-fonts-3

    Feel free to add what you need
// -->
<ul class="social-links">
    <li><a href="http://www.facebook.com/summerfestivalguide" target="_blank" title="Facebook"><i class="fi-social-facebook"></i></a></li><!-- Facebook -->
    <li><a href="https://plus.google.com/b/113524402586185730024/113524402586185730024/posts" target="_blank" title="Google+"><i class="fi-social-google-plus"></i></a></li><!-- Google + -->
    <li><a href="http://www.twitter.com/ukfestivalguide" target="_blank" title="Twitter"><i class="fi-social-twitter"></i></a></li><!-- Twitter -->
    <li><a href="http://www.flickr.com/photos/summerfestivalguide" target="_blank" title="Flickr"><i class="fi-social-flickr"></i></a></li>

  <!--<li><a href="#" target="_blank" title="Delicious"><i class="fi-social-delicious"></i></a></li>  Delicious -->
    <!--<li><a href="#" target="_blank" title="Digg"><i class="fi-social-digg"></i></a></li> Digg -->
    <!-- <li><a href="#" target="_blank" title="Dribbble"><i class="fi-social-dribbble"></i></a></li> Dribble -->  
    <!--<li><a href="#" target="_blank" title="Flickr"><i class="fi-social-flickr"></i></a></li> Flickr -->    
    <!--<li><a href="#" target="_blank" title="Foursquare"><i class="fi-social-foursquare"></i></a></li> Foursquare -->
    <!--<li><a href="#" target="_blank" title="Github"><i class="fi-social-github"></i></a></li> Github -->    
    <!--<li><a href="#" target="_blank" title="Instrgram"><i class="fi-social-instagram"></i></a></li> Instragram -->
    <!--<li><a href="#" target="_blank" title="LinkedIn"><i class="fi-social-linkedin"></i></a></li> LinkedIn -->    
    <!--<li><a href="#" target="_blank" title="Skype"><i class="fi-social-skype"></i></a></li> Skype -->
    <!--<li><a href="#" target="_blank" title="Tumblr"><i class="fi-social-tumblr"></i></a></li> Tumblr -->    
    <!--<li><a href="#" target="_blank" title="Vimeo"><i class="fi-social-vimeo"></i></a></li> Vimeo -->
    <!--<li><a href="#" target="_blank" title="YouTube"><i class="fi-social-youtube"></i></a></li> YouTube-->
    <!--<li><a href="#" target="_blank" title="Stack Overflow"><i class="fi-social-stack-overflow"></i></a></li> Stack Overflow -->
</ul>   